### ISSUE TITLE
Support floats

### ISSUE THREAD

**Issue by filib** [filib/ruby-marshal#12]
Depends on https://github.com/filib/ruby-marshal/issues/3.

**Comment by filib** [comment]
@adinapoli Floats are just encoded as raw byte strings. Any suggestions to go from `"3.333" :: ByteString` to `Double`?

**Comment by adinapoli** [comment]
What about the simple way?

``` haskell
import Data.String.Conv
import Data.ByteString
import Data.Read

let (b :: Bytestring) = "3.333"
let (res :: Maybe Double) = readMaybe . toS $ b
```
