### ISSUE TITLE
Support strings

### ISSUE THREAD

**Issue by filib** [filib/ruby-marshal#3]

**Comment by adinapoli** [comment]
Any pointer to where the specification (in terms of the JRuby implementation) can be found?

**Comment by filib** [comment]
From a blog post giving an overview of ivars and strings:

http://jakegoulding.com/blog/2013/01/16/another-dip-into-rubys-marshal-format/

From the JRuby source:

https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyString.java#L5220-L5224
https://github.com/jruby/jruby/blob/3485ab608b89dc31e7de71493f719a93d168900e/core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java#L294-L309

**Comment by filib** [comment]
There's also a an implementation in `go` which might be easier to navigate than the JRuby codebase.

https://github.com/adjust/gorails/blob/master/marshal/marshal.go

**Comment by adinapoli** [comment]
Quite nice to see we were not the only folks trying to do this.

**Comment by filib** [comment]
Yeah, that's true. I think the `go` implementation emerged first because so many Ruby defectors have moved to `go` in recent times. 

They conveniently also worked on supporting Rails sessions and probably where we should go next once we have a subset of necessary Ruby objects. https://github.com/adjust/gorails/tree/master/session

**Comment by filib** [comment]
Go here next https://github.com/filib/ruby-marshal/issues/16.
