### ISSUE TITLE
Prepare for public release

### ISSUE THREAD

**Issue by filib** [filib/ruby-marshal#40]
- [x] Polish README.
- [x] Use a proper Map instead of Vector (a, b) for RHash.
- [x] Re-consider Ivar API - should consumers have to deal with character encodings themselves?
- [x] Minor code shuffling.
- [x] Ask for feedback [[link](https://www.reddit.com/r/haskell/comments/3enysr/my_first_haskell_project_a_ruby_marshal_parser/)]
- [x] Push to Hackage.

**Comment by adinapoli** [comment]
Yay!

**Comment by filib** [comment]
@adinapoli couldn't have done it without your help, dude!

:sparkler:

**Comment by adinapoli** [comment]
:tada:
